title: Ahmad Raza Portfolio
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
baseurl: "/cybersec"

# This plugin tells GitHub to safely download the theme for you
plugins:
  - jekyll-remote-theme
