title: Ahmad Raza Portfolio
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true

# This tells the theme to load styles inside your specific repository folder
baseurl: "/CyberSec"
